version: '3.8'

services:
  glpi-web:
    build: .
    container_name: glpi-web-dashboard
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: python3 src/app.py

  glpi-notifier:
    build: .
    container_name: glpi-notifier
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: python3 src/glpi_to_teams.py
